apiVersion: apps/v1
kind: Deployment
metadata:
  name: nt-server-dep
  namespace: dev
spec:
  selector:
    matchLabels:
      app: nt-server
  template:
    metadata:
      labels: 
        app: nt-server
    spec:
      containers:
        - name: nt-server
          image: adenli/ntserver:dev-59a7210
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: nt-server-srv
  namespace: dev
spec:
  type: ClusterIP        # internal only
  selector:
    app: nt-server
  ports:
    - port: 3001         # service port inside cluster
      targetPort: 3001   # container port
